### ISSUE TITLE
Улучшение парсинга ссылок

### ISSUE THREAD

**Issue by xenolOnline** [almirus/TinkoffTicker#10]
Плагин плохо получает ссылки с сайта seekingalpha.com - связываю это с загрузкой сайта ajaxom - есть возможность отложенного парсинга регуляркой? Например спустя пару секунд после загрузки?

**Comment by almirus** [comment]
думал над этим, но это пока похоже на велосипед :(

**Comment by xenolOnline** [comment]
А можно сделать кнопку на плагине, чтобы парсинг происходил по нажатию кнопки?

**Comment by almirus** [comment]
как вариант. самый простой. плавающую кнопку
второй вариант реагировать на изменения DOM дерева.

**Comment by xenolOnline** [comment]
Думаю, кнопки вполне хватит и это должно решить почти все проблемы)
