### ISSUE TITLE
Все сломалось))

### ISSUE THREAD

**Issue by xenolOnline** [almirus/TinkoffTicker#12]
Плагин перестал работать  - синтаксическая ошибка
 chrome-extension://dpflhleimmbhmcihedanghbdeoinpiig/js/content.js:43 Uncaught SyntaxError: Unexpected token '||='

**Comment by almirus** [comment]
можешь проверить в коде там так?

                        tail ||= option.activelink ? '⧉' : '';
у меня работает, версия 1.0.2

**Comment by xenolOnline** [comment]
да, именно здесь, версия 1.02
яндекс браузер 20.8.0.893 (64-bit)

строчка написана именно так

**Comment by almirus** [comment]
но это синтаксически верно. можешь попробовать в chrome

**Comment by xenolOnline** [comment]
да, работает в хроме Версия 85.0.4183.83

**Comment by almirus** [comment]
Интересно деффки пляшут 😊 впервые встречаю такое
сейчас сделаю фикс для yandex, но выкатываться будет соответственно не быстро

**Comment by almirus** [comment]
отправлено на апруф гуглу
