### ISSUE TITLE
Неверно показывает тикер на золото

### ISSUE THREAD

**Issue by lifegifted** [almirus/TinkoffTicker#13]
Вместо FXGD или пусто показывает ZG - Zillow
<img width="951" alt="Снимок экрана 2021-02-19 в 14 19 16" src="https://user-images.githubusercontent.com/20501509/108498265-aa828d00-72bd-11eb-9d29-2c0f0a43aab8.png">

**Comment by almirus** [comment]
к сожалению это никак не исправить, алгоритм очень простой, берется тикер (регулярное выражение), в данном случае ZG и он ищется поиском у Тинькофф Брокера, этому тикеру соответствует бумага Zillow

**Comment by almirus** [comment]
можно пока придумать только сделать кастомную автозамену одного найденного тикера на другой у брокера

**Comment by lifegifted** [comment]
При условии что тинкоф не торгует золотом напрямую - мне кажется нужно вообще убрать.

**Comment by almirus** [comment]
для этого есть черный список тикеров
