### ISSUE TITLE
Пара мелких фич для удобства

### ISSUE THREAD

**Issue by beitan** [almirus/TinkoffTicker#6]
- Выбор цвета подсветки тикера

- Возможность отключать подсветку тикеров из премиум-списка

Спасибо.

**Comment by almirus** [comment]
это уже реализовано
![image](https://user-images.githubusercontent.com/16898685/88768574-f3d58880-d183-11ea-9a9b-a550e6b4fc5e.png)

проверьте версию установленного плагина 0.0.7 - самая свежая

**Comment by beitan** [comment]
Имеется в виду менять цвет текста тикера (желтый, пример с финвиза)

![image](https://user-images.githubusercontent.com/68656340/88772955-24b8bc00-d18a-11ea-8c80-35e772cfcf98.png)
