### ISSUE TITLE
Доступность в лонг и CSS на earningswhispers.com

### ISSUE THREAD

**Issue by beitan** [almirus/TinkoffTicker#8]
Спасибо за отличную работу! Есть пара мелких багов:

- Не показывает доступность бумаг (VTR, как пример) в лонг

![image](https://user-images.githubusercontent.com/68656340/89624803-799db600-d89f-11ea-8bde-854b15093862.png)

бумаги есть в списке маржинальных

![image](https://user-images.githubusercontent.com/68656340/89625006-c1244200-d89f-11ea-853b-37836193df8b.png)

- Не применяются кастомные CSS к тикерам на [https://www.earningswhispers.com/calendar](https://www.earningswhispers.com/calendar)

**Comment by almirus** [comment]
исправлено в версии 0.0.9
